version: '3.7'
services:
#  mongodb:
#    container_name: mongodb
#    image: mongo
#    init: true
#    restart: always
#    ports:
#    - 27017:27017
#    environment:
#      MONGO_INITDB_DATABASE: instaconnect
#    networks:
#      - network
#    volumes:
#    -  $HOME/data/db:/data/db
#    - $HOME/data/bkp:/date/bkp

  app-server:
    container_name: app-server
    build: .
    ports:
    - "8080:8080"
    restart: always
#    depends_on:
#      - mongodb
    networks:
      - network
#    links:
#      - mongodb

networks:
  network:
    driver: bridge