spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: instaconnect
  servlet:
    multipart:
      max-file-size: 50MB

amazon:
  accessKey: accessKey
  secretKey: secretKey
  bucket:
    profilePicture: connect-profile-picture